name: "generate-pixel-github-stats"
description: "Generates a github stats card from a github user contributions."
author: "LuciNyan"

runs:
  using: node20
  main: libs/index.js

inputs:
  github_token:
    description: "github token used to fetch the contribution data. Default to the action token if empty."
    required: false
    default: ${{ github.token }}
  outputs:
    required: false
    default: null
    description: |
      list of files to generate.
